language: python
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get -y install python python-dev python-pip
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create database ctfcal;' -U postgres
services:
  - postgresql
script:
  - coverage run --source . -m pytest -v && coverage report
after_success:
  coveralls
notifications:
  email: false
